---
server:
  port: 8080
...
---
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/roncoo/spring-cloud-demo.git
          search-paths: spring-cloud-02-consumer
...