---
server:
  port: 8080
...
---
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lewis-java/springcloud_example
          search-paths: /springcloud-discover-eureka/src/main/resources**
        default-label: master
...